package com.noh.zup.domain.collection;

public enum SkippedReason {
    ROBOTS_TXT_DISALLOWED,
    ROBOTS_TXT_FETCH_FAILED,
    ROBOTS_TXT_PARSE_FAILED,
    TERMS_RESTRICTION_FOUND,
    TERMS_BLOCKED,
    TERMS_NOT_CHECKED,
    COLLECTION_PERMISSION_NOT_APPROVED,
    LOGIN_REQUIRED_SOURCE,
    LOGIN_REQUIRED,
    POLICY_NEEDS_REVIEW,
    UNKNOWN_POLICY_NEEDS_REVIEW
}
